sudo: required
dist: trusty

install:
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script:
  - docker ps -a

after_script:
  - docker-compose down

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
  - dev