version: "3"

services:
  app:
    build: .
    container_name: app.server
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/app/
    environment:
      - C_FORCE_ROOT=true
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    container_name: app.postgres
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - postgres-conf:/etc/postgresql
      - postgres-logs:/var/log/postgresql

    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: n34SeCrFv0f
      POSTGRES_DB: short_url_db

    networks:
      - app-network

volumes:
  postgres-data:
  postgres-conf:
  postgres-logs:

networks:
  app-network:
    driver: bridge
